### ISSUE TITLE
How to implement on MainActivity.java & IOS

### ISSUE THREAD

**Issue by wernerkotze** [Pantrist-dev/capacitor-firebase-dynamic-links#1]
Hi There,

First of all, thank you for updating the package to capacitor 3.

Could you please assist me to implement this in MainActivity.java and IOS app.

**Comment by askilondz** [comment]
You shouldn't have to do anything in MainActivity.java for Capacitor 3. iOS should also work out of the gate without any extra needed implementation. Just make sure you run `npx cap sync` after installing this plugin.

**Comment by NLueg** [comment]
@wernerkotze sorry for the late response I have not received any notification for your issue ... 
But it's like @askilondz said you don't have to do anything for both platforms since Capacitor 3.
