### ISSUE TITLE
removeAllListener method is not working on iOS

### ISSUE THREAD

**Issue by priyanshmishra1611** [Pantrist-dev/capacitor-firebase-dynamic-links#11]
`removeAllListeners()` is not working on iOS. It is showing as method not defined.

Same method & code is working perfectly fine on Android.
It is removing all CapacitorDynamicLink listeners in Android.

Can you please check the issue in Plugin

**Comment by NLueg** [comment]
Hi there, thanks for reporting the issue! 
Just solved the issue and published it as version `1.1.1`.
