### ISSUE TITLE
The documentation is a bit unclear on which config steps to perform 

### ISSUE THREAD

**Issue by madmacc** [Pantrist-dev/capacitor-firebase-dynamic-links#12]
The documentation is a bit unclear on which steps to perform here:

>  iOS
> Configure your app to use dynamic links based on the official Firebase documentation. You only need to apply the steps 1-3 of the following guid:
> 
> https://firebase.google.com/docs/dynamic-links/ios/receive

I assume it means the first 3 steps here and we ignore steps 4 onward?:
https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app

> 1.
> In the Info tab of your app's Xcode project, create a new URL type to be used for Dynamic Links. Set the Identifier field to a unique value and the URL scheme field to be your bundle identifier, which is the default URL scheme used by Dynamic Links.
> 
> 2.
> In the Capabilities tab of your app's Xcode project, enable Associated Domains and add the following to the Associated Domains list:
> 
> applinks:your_dynamic_links_domain
> 
> 3.
> If you want to receive Dynamic Links with a [fully-custom domain](https://firebase.google.com/docs/dynamic-links/custom-domains), in your Xcode project's Info.plist file, create a key called FirebaseDynamicLinksCustomDomains and set it to your app's Dynamic Links URL prefixes. For example:
> 
> FirebaseDynamicLinksCustomDomains
> 
>   https://example.com/promos
>   https://example.com/links/share

**Comment by NLueg** [comment]
Hello @madmacc, thank you for creating the issue!
Yes, you only have to follow the first three steps.

I don't add the documentation by myself because Firebase translates the instructions to multiple languages, which might be helpful for some people. But I could write the steps by myself and just add the link as reference.
Just updated the docs to clarify it.
