### ISSUE TITLE
iOS the creation of Dynamic Short link is not working

### ISSUE THREAD

**Issue by priyanshmishra1611** [Pantrist-dev/capacitor-firebase-dynamic-links#16]
The method name `createDynamicShortLink` is working on Android for creating shortLinks for FirebaseDynamicLink but in iOS it is always giving error

> {"message":"Unable to create link","errorMessage":" "}

I have tested in iOS 15.5 
Iphone 6s.

Please look into the issue

**Comment by NLueg** [comment]
Hey @priyanshmishra1611 can you attach the parameter you're using to create the link?

**Comment by priyanshmishra1611** [comment]
I have padded params:
```
{
domainUriPrefix:"https://maximl.page.link/".
uri:"CURRENT_PAGE_URI"
}
```

@NLueg

**Comment by NLueg** [comment]
Can you try to set the bundle ID for your iOS parameters? 
It at least is also set in the official example of Firebase here: https://firebase.google.com/docs/dynamic-links/ios/create
Maybe the iOS implementation is stricter than the iOS implementation.
For your case, you could try:

```ts
{
  domainUriPrefix:"https://maximl.page.link/".
  uri:"CURRENT_PAGE_URI",
  iosParameters: {
    bundleId: '<your_bundle_id>'
  }
}
```

**Comment by priyanshmishra1611** [comment]
Still i am getting same error 

@NLueg 
<img width="975" alt="Screenshot 2022-06-02 at 6 49 42 PM" src="https://user-images.githubusercontent.com/103493365/171638649-08980e33-edd5-410b-a627-9c67ecf09aba.png">

**Comment by priyanshmishra1611** [comment]
HI @NLueg ,
Any update on the iOS issue i have raised ?

**Comment by LiamKarlMitchell** [comment]
In Safari debugging simulator I am seeing an error.

```
Error: "CapacitorFirebaseDynamicLinks" plugin is not implemented on ios
```

**Comment by NLueg** [comment]
Hey @priyanshmishra1611, sorry for the late response.
I actually have no idea what could be the issue here. 
The only thing I could think about is that you need more parameters for iOS. Could you try to set the following parameters (of course with your links and IDs):

```ts
{
   ...
    iosParameters: {
        fallbackUrl: 'https://maximl.page.link/<link>',
        bundleId: '<your-bundle-id>',
        appStoreId: '<your-app-store-id>',
        ipadBundleId: '<your-bundle-id>',
        ipadFallbackUrl: 'https://maximl.page.link/<link>,
    },
}
```

**Comment by NLueg** [comment]
> In Safari debugging simulator I am seeing an error.
> 
> ```
> Error: "CapacitorFirebaseDynamicLinks" plugin is not implemented on ios
> ```

This is actually a bit off-topic in this issue, but this is a more or less common issue when installing a new package.
A `npx cap sync ios` should do the thing here.
You can find more about this here: https://capacitorjs.com/docs/ios/troubleshooting#plugin-not-implemented

**Comment by LiamKarlMitchell** [comment]
Confirming that I can createDynamicShortLink by providing just the domainUriPrefix and the uri to fallback on iPhone 13.
As well as receive the short link in my main entry point and take any necessary action for routing.


Thanks, sorry for my new ness, I had to upgrade the capacitor version from 2.0.0 to 3.6.0 then it worked after using the sync command and building. I had to increase the iOS min version from 11 to 12 in capacitor.config.json as well for the pods to work it seemed.


```json
"ios": {
    "minVersion": "12.0"
  }
```

createDynamicLink is always returning undefined however probably a different problem. Maybe there are some more required options I'll check the firebase docs thanks.

This one works, but since I copied this I have added the iOS app/bundle/fallback details.
```typescript
export function createShortLink(link: string): Promise<string> {
  const config: LinkConfig = {
    domainUriPrefix: 'https://mycustomapp.page.link',
    uri: link
  };
  return FirebaseDynamicLinks.createDynamicShortLink(config).then(link => link.value)
}
```

Import is direct to the plugin like this.
```typescript
import { FirebaseDynamicLinks, LinkConfig } from '@pantrist/capacitor-firebase-dynamic-links';
```

Code for createDynamicLink looks like this, couldn't get it to work which is probably fine short links are nice too.
```typescript
const config: LinkConfig = {
  domainUriPrefix: 'https://mycustomapp.page.link',
  uri: 'https://mycustomapp.page.link/invite?code=' + invite_code,
  //androidParameters?: AndroidParameters; // I'm not using Android.
  iosParameters: {
    fallbackUrl: 'https://www.myWebsiteHere.com/invite?code=' + invite_code,
    bundleId: 'MyBundleIdHere',
    appStoreId: 'MyAppStoreIdHere',
    ipadBundleId: 'MyAppStoreIdHere',
    ipadFallbackUrl: 'https://www.myWebsiteHere.com/invite?code=' + invite_code,
  }
};

const result = await FirebaseDynamicLinks.createDynamicLink(config);
console.log(`Result Dynamic Link: ${result.value}`);
```

my src-capacitor package.json dependencies look like.

```
    "@capacitor/app": "^1.1.1",
    "@capacitor/cli": "^3.6.0",
    "@capacitor/core": "^3.6.0",
    "@capacitor/splash-screen": "^1.2.2",
    "@capacitor/share": "^1.1.2",
    "@pantrist/capacitor-firebase-dynamic-links": "^1.1.2"
```

**Comment by NLueg** [comment]
Hey @LiamKarlMitchell hm, that's strange. Do you also have the `@capacitor/ios` dependency installed?
What is the CLI output when you run `ionic cap sync ios`?

**Comment by LiamKarlMitchell** [comment]
Yeah, I've already put a build into test flight :)
createDynamicLink just fails, but the short link works so I probably just have the wrong parameters.
Was able to get a short link that opens the app or takes to store for iOS though :)

**Comment by NLueg** [comment]
Ah great, so your issue is solved?
