### ISSUE TITLE
iOS - Deep Link does not contain valid required params.

### ISSUE THREAD

**Issue by swapnaliDeveloper** [Pantrist-dev/capacitor-firebase-dynamic-links#17]
Link is created with function createDynamicShortLink with following linkConfiguration
const config: LinkConfig = {
          domainUriPrefix: "https://....",
          uri: uristring,
          androidParameters: {
            packageName: "...."
          },
          iosParameters: {
            bundleId : "...",
            appStoreId : "...", 
            fallbackUrl :  "...", 
            ipadFallbackUrl :  "...", 
            ipadBundleId :  "...", 
            customScheme :  "...", 
            minimumVersion :  "...", 
          }
        };

Android - working perfectly
iOS - getting "Deep Link does not contain valid required params." error 
Which parameters are missing  ? 

Also all ios configuration is done by official documents https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app

**Comment by NLueg** [comment]
Hey @swapnaliDeveloper could you try to check the following stackoverflow question? It seems to be a similar issue: https://stackoverflow.com/questions/54294267/deep-link-does-not-contain-valid-required-params-while-clicking-a-dynamic-link
If it doesn't help you, I need some more information about what you pass inside the `uri`. Thanks!

**Comment by swapnaliDeveloper** [comment]
Hi @NLueg , 
I have tried all encoding ways ... it seems related to long url ...but in my app i m using createDynamicShortLink function 
my app uri structure like 
uri : "https://app.xxxxxx.com?param1=" +param1 + "&param2=" + param2  ; 

also i have tried out without the special char like 
uri : "https://app.xxxxxx.com?" + param1;

But getting same output as mentioned

**Comment by NLueg** [comment]
Hello @swapnaliDeveloper! Hmm ... quite hard to say actually what the issue is here.
I actually also use a quite complex link for my app, so your link should also work as expected. 

I have done some research and this seems to be a quite common issue with dynamic links. The problem may lie in the link itself, can you check if you have any warnings on the firebase page as described here? https://firebase.google.com/docs/dynamic-links/debug

**Comment by NLueg** [comment]
Closed, as there is no more progress in this issue. If you still experience an issue, you can of course reopen it.
