### ISSUE TITLE
Capacitor4 Docs Conflics with README

### ISSUE THREAD

**Issue by selcuk-sahin** [Pantrist-dev/capacitor-firebase-dynamic-links#19]
In the README plugin is registered **after** the registerPlugin function
But Capacitor 4 wants plugins to make it **before** the registerPlugin

https://capacitorjs.com/docs/updating/4-0#change-registerplugin-order

Should we still register this plugin or can we remove it?

> 
> ### Android
> 
> In file `android/app/src/main/java/**/**/MainActivity.java`, add the plugin to the initialization list:
> 
> ```java
> import com.pantrist.firebase.dynamiclinks.CapacitorFirebaseDynamicLinks;
> 
> public class MainActivity extends BridgeActivity {
>    @Override
>    public void onCreate(Bundle savedInstanceState) {
>       super.onCreate(savedInstanceState);
>       ...
>       registerPlugin(CapacitorFirebaseDynamicLinks.class);
>    }
> }
> ```

**Comment by NLueg** [comment]
Hey @selcuk-sahin! Thank you for mentioning this.
No, you're right. This is not required at all. I removed this from the `README`.
Thanks!
