### ISSUE TITLE
[Capacitor Plugin Error] - createDynamicLink

### ISSUE THREAD

**Issue by reubenwedson** [Pantrist-dev/capacitor-firebase-dynamic-links#21]
I'm not getting the long link, using capacitor 4
`[Capacitor Plugin Error] - CapacitorFirebaseDynamicLinks - createDynamicLink - Unable to serialize plugin response as JSON.Ensure that all data passed to success callback from module method is JSON serializable!`

despite having the log from xcode 
`⚡️  To Native ->  CapacitorFirebaseDynamicLinks createDynamicLink 65776433
The long URL is: {shows the link here}`

**It works fine on android**

**Comment by NLueg** [comment]
Thank you for submitting the issue.
Can you share, what data you're passing to the plugin? You can change your specific IDs in strings, of course.

**Comment by reubenwedson** [comment]
`const config: LinkConfig = {
      domainUriPrefix: 'https://example.page.link',
      uri: 'https://example.page.link/sharing',
   };
`
only passing _domainUriPrefix_ and _uri_
@NLueg

**Comment by NLueg** [comment]
Thanks for your fast response! I just published the version `4.0.2` which should solve the issue.
Could you check this in your app? Thanks!

**Comment by reubenwedson** [comment]
@NLueg I confirm that it works now, Thank you.
