### ISSUE TITLE
Unable to import package without SyntaxError

### ISSUE THREAD

**Issue by alectoparty** [Pantrist-dev/capacitor-firebase-dynamic-links#22]
Unable to implement package in my project, seems to be an issue with

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.@pantrist/capacitor-firebase-dynamic-links

**Comment by NLueg** [comment]
Can you provide some more details? What Capacitor-Version are you using? What module did you set in your `tsconfig`?

**Comment by alectoparty** [comment]
Thanks @NLueg It is a server-side rendered next.js implementation of react.js. It is a javascript project, but i have not experienced issues importing .ts modules in the past. I believe all capacitor packages are .ts and work fine.

Capacitor version  
    "@capacitor/app": "^4.1.0",
    "@capacitor/core": "^4.0.0",
    "@capacitor/device": "^4.0.1",
    "@capacitor/ios": "^4.0.0",

**Comment by xurshid29** [comment]
Same problem

"module": "esnext"

![image](https://user-images.githubusercontent.com/5887811/213884613-931bd793-b9db-46ed-b8f4-bc62cca16738.png)

**Comment by xurshid29** [comment]
I think this package should also support CommonJS syntax, not just ESModule.

**Comment by NLueg** [comment]
> I think this package should also support CommonJS syntax, not just ESModule.

Sure, I would love to! Do you know how we can accomplish that?

**Comment by xurshid29** [comment]
> Sure, I would love to! Do you know how we can accomplish that?

I think it's very well explained in this doc page: Dual CommonJS/ES module packages - https://nodejs.org/api/packages.html#dual-commonjses-module-packages

**Comment by NLueg** [comment]
I just published version `4.1.0` which should solve the issue. Could you verify it?

**Comment by alectoparty** [comment]
It now lets me import it successfully into my project, but causes my capacitor builds to fail. Debug says "unable to open configuration settings file" and "missing module map file: [link to file here]"

I will also add that it sometimes fully builds and downloads but it fails to load app

**Comment by NLueg** [comment]
Hmm, that's strange. The `map.js` is also part of the package when I install it. Could you provide me a minimum example in a repository, so that I can reproduce the issue?

**Comment by NLueg** [comment]
I will close the issue for now as there is no further progress. I think it should work with the newest version. If this is not the case, feel free to reopen the issue!
