### ISSUE TITLE
Error: "CapacitorFirebaseDynamicLinks.createShortLink()" is not implemented on android

### ISSUE THREAD

**Issue by Zeusmist** [Pantrist-dev/capacitor-firebase-dynamic-links#25]
I get the error below when I try to call createShortLink as shown in the README
![image](https://user-images.githubusercontent.com/51177741/220915872-6fd3b855-5365-4bad-aa72-ac67f7f2c9ea.png)

I am using Capacitor v4

I already ran `npx cap sync` and added **google-services.json** 

Here is a snippet of my code:
![image](https://user-images.githubusercontent.com/51177741/220916769-db2ad2c7-1a7b-4237-801f-b492d879be45.png)

Please any idea why I might be having this error?

**Comment by Zeusmist** [comment]
Fixed in this PR https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/pull/26

**Comment by NLueg** [comment]
Thank you for your investigation and fixing the issue.
