### ISSUE TITLE
Warning about JVM version During Android build phase

### ISSUE THREAD

**Issue by selcuk-sahin** [Pantrist-dev/capacitor-firebase-dynamic-links#28]
Hi have a good day, 
I'm getting this warning when building for Android:

> 'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

I understand the JVM version between Kotlin & Java doesn't match.
with Capacitor4, JVM version should be 11 (ref:[Capacitor4 Update DOC](https://capacitorjs.com/docs/updating/4-0#ensure-you-are-using-java-11))

**Comment by NLueg** [comment]
Hey there! This actually should be the case right now. Are you sure, that your configuration is correct?
The plugin builds with Java 11: https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/blob/5dc8719b46105aa6dcf5510a63fbdf7fc7910474/android/build.gradle#L44, also I'm not getting any warning when I build android for my app.

**Comment by selcuk-sahin** [comment]
Thanks for the quick reply, I narrowed down this warning a bit more.

This warning is only seen in the first build/compile after cleaning a project. 

Since I saw the warning is related to a kotlin task, I experimented with this code & received no further warnings.

```diff java
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
+    kotlinOptions {
+       jvmTarget = JavaVersion.VERSION_11
+    }
```

**Comment by NLueg** [comment]
Aaah okay nice. Thanks for specifying this!
I will add this piece of code so that the warning will be solved for the next release.

**Comment by NLueg** [comment]
I just released a version for `Capacitor 5` which also solves this issue in version `5.0.1`.
