### ISSUE TITLE
Deferred deeplink information

### ISSUE THREAD

**Issue by Saqib92** [Pantrist-dev/capacitor-firebase-dynamic-links#29]
In my capacitor app I am already using Capacitor deeplinks via [Capacitor Deeplink](https://capacitorjs.com/docs/guides/deep-links). 

I already have website, android and iOS working. 
My Deeplink: `https://www.example.com/user/123` etc 
When user clicks on this link it opens my app. 

Now, if user don't have my app installed i want them to go to appstore or playstore and install app then redirect them to clicked link after installation. 

Now my question is how can i setup firebase dynamic deeplinks?

**Comment by NLueg** [comment]
Hey @Saqib92, sorry for the late response! 
It would be best if you would follow the documentation that Firebase provides, e.g. here: https://firebase.google.com/docs/dynamic-links

There are also some guides out there that should help with creating the links. After you create the links as said in the documentation it should work exactly how you want it. 

I will close the issue. If you have any specific questions or trouble while including the plugin feel free to reopen the issue 😄
