### ISSUE TITLE
Support Capacitor 5.0

### ISSUE THREAD

**Issue by typefox09** [Pantrist-dev/capacitor-firebase-dynamic-links#30]
IS there any plans to support Capacitor 5? The change list looks minimal so it should be a quick fix.

**Comment by NLueg** [comment]
Thanks for your issue! Of course, I want to add support for Capacitor 5. I will have a look at it today.

**Comment by NLueg** [comment]
I just published version `5.0.1` which should support Capacitor 5. I tried it with the latest Release-Candidate and it should work. If this is not the case, feel free to reopen the issue!
