### ISSUE TITLE
NPM version 5.0.1 source code is not available on github

### ISSUE THREAD

**Issue by e-e-e** [Pantrist-dev/capacitor-firebase-dynamic-links#34]
It looks like the version of this library available on [npm](https://www.npmjs.com/package/@pantrist/capacitor-firebase-dynamic-links) has not been pushed to this repository.

**Comment by NLueg** [comment]
Oh wow, what a shame ...
Yes, you're correct. I now pushed everything. Thank you so much for the reminder!

**Comment by e-e-e** [comment]
Thanks so much for fixing this so quickly. Its appreciated.
