### ISSUE TITLE
Dynamic short link successfully created and working but not listed on Firebase Dynamic Links

### ISSUE THREAD

**Issue by orestis-z** [Pantrist-dev/capacitor-firebase-dynamic-links#35]
Hello,

I can successfully create dynamic short links with this plugin and I've verified that they work. E.g. I can open the app through a deep link and listen to `FirebaseDynamicLinks.addListener("deepLinkOpen", cb)`.

However, the generated short links are not listed under the Firebase deep links.

Is this expected?

P.S. It's not a matter of delays since I've waited multiple days

<img width="1060" alt="Screenshot 2023-11-17 at 12 58 27" src="https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/assets/23146389/f34a4730-c0ba-4765-8a47-0a0f65b13488">

**Comment by luantrasel** [comment]
yes it is expected, only links created directly on the Firebase interface are visible there

**Comment by orestis-z** [comment]
Thanks for letting me know
