### ISSUE TITLE
Is pod 'Firebase/Analytics' really necessary?

### ISSUE THREAD

**Issue by luantrasel** [Pantrist-dev/capacitor-firebase-dynamic-links#36]
Hi there,

I'm using your plugin for quite a while but now I'm having problems on a new project. Having the pod 'Firebase/Analytics' is causing me some weird memory errors when running the app. I found that it was because the pod 'Firebase/Analytics'. After I removed the pod everything went fine and my problem is gone.

For what I tested, everything continues to work even without this pod.

Is there a reason for this pod? Can it be removed (I can create a PR if so)?

**Comment by NLueg** [comment]
Hello, thank you for the report!
I just tried it out and it actually doesn't change anything. I published "5.0.2" where the dependency is removed.
