### ISSUE TITLE
[android] NullPointerException caused by missing check for iOS parameters

### ISSUE THREAD

**Issue by Lernni** [Pantrist-dev/capacitor-firebase-dynamic-links#37]
If you want to create a dynamic short link without providing ios parameters, the app crashes with the following NullPointerException:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getcapacitor.JSObject.getString(java.lang.String)' on a null object reference
	at com.pantrist.firebase.dynamiclinks.CapacitorFirebaseDynamicLinks.buildIOSParameters(CapacitorFirebaseDynamicLinks.kt:119)
	at com.pantrist.firebase.dynamiclinks.CapacitorFirebaseDynamicLinks.createDynamicShortLink(CapacitorFirebaseDynamicLinks.kt:72)
```

A solution to this problem would be to add the missing check in [CapacitorFirebaseDynamicLinks.kt](https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/blob/cfba1815efd7169065ff5e7bca6ddd25f96a4aa6/android/src/main/java/com/pantrist/firebase/dynamiclinks/CapacitorFirebaseDynamicLinks.kt#L119), that `iosParameters` is defined properly before trying to access the object:

```kt
private fun buildIOSParameters(call: PluginCall, builder: DynamicLink.Builder) {
	val iosParameters = call.getObject("iosParameters")
	
	if (iosParameters != null && iosParameters.getString("bundleId") != null) {
		// ...
	}
}
```

**Comment by NLueg** [comment]
Thank you for creating the issue! I just solved the it in 035774e and published it in version `5.0.3`
