### ISSUE TITLE
improve a little the readme

### ISSUE THREAD

**Issue by KernelFolla** [Pantrist-dev/capacitor-firebase-dynamic-links#5]
this plugin works fine but to make it working I had to study and debug because I've used the class CapacitorFirebaseDynamicLinks instead of FirebaseDynamicLinks with the result that events aren't registered and triggered. I think a couple of lines with an example like this can be enough:

```typescript
import {FirebaseDynamicLinks} from '@pantrist/capacitor-firebase-dynamic-links'; 
// ...
FirebaseDynamicLinks.addListener('deepLinkOpen', (data: { url: string }) => {
    // ....
);
```

do you need a PR for this?

**Comment by NLueg** [comment]
Thanks for your issue! I just added an example that clarifies the usage of the plugin
