### ISSUE TITLE
Fix Bintray issue

### ISSUE THREAD

**Issue by sneko** [Pantrist-dev/capacitor-firebase-dynamic-links#8]
Hi,

Just posted the fix for Bintray discontinuation here https://github.com/ClipboardHealth/capacitor-firebase-dynamic-links/issues/9 but it appears someone did it on your repo already https://github.com/Pantrist-dev/capacitor-firebase-dynamic-links/commit/5b95668d374725ad258e305ce41de87e5550c1be

That's great but for me I had to remove also bintray reference in the `repositories {}` section.

Maybe that's specific to me? Just leaving the info here in case :)

**Comment by NLueg** [comment]
Hey @sneko! Yes, after some research, I think that you're right.
I just removed this repository too. I won't release a new version specifically for this change, as this currently doesn't break anything.
Thanks for reporting this!
